"""Take GitLab actions based on a PolicyReceipt."""

from __future__ import annotations

from typing import Any

import httpx

from .policy_engine import PolicyReceipt, Verdict


class GitLabActions:
    def __init__(self, gitlab_url: str, token: str, project_id: int | str):
        self._base = gitlab_url.rstrip("/")
        self._project_id = project_id
        self._headers = {"PRIVATE-TOKEN": token, "Content-Type": "application/json"}

    def _post(self, path: str, body: dict[str, Any]) -> dict[str, Any]:
        resp = httpx.post(
            f"{self._base}{path}",
            headers=self._headers,
            json=body,
            timeout=15,
        )
        resp.raise_for_status()
        return resp.json()

    def handle(self, receipt: PolicyReceipt, mr_iid: int | None = None) -> dict[str, Any]:
        if receipt.verdict == Verdict.REACHABLE:
            return self._escalate(receipt, mr_iid)
        else:
            return self._deprioritize(receipt, mr_iid)

    def _escalate(self, receipt: PolicyReceipt, mr_iid: int | None) -> dict[str, Any]:
        body = self._receipt_comment(receipt)
        work_item = self._create_work_item(
            title=f"[ReachGate] Reachable: {receipt.occurrence_name}",
            description=body,
            labels=["reachgate::reachable", f"severity::{receipt.severity}"],
        )
        if mr_iid:
            self._post_mr_comment(mr_iid, body)
        return {"action": "escalated", "work_item": work_item}

    def _deprioritize(self, receipt: PolicyReceipt, mr_iid: int | None) -> dict[str, Any]:
        body = self._receipt_comment(receipt)
        if mr_iid:
            self._post_mr_comment(mr_iid, body)
        return {"action": "deprioritized"}

    def _create_work_item(
        self, title: str, description: str, labels: list[str]
    ) -> dict[str, Any]:
        return self._post(
            f"/api/v4/projects/{self._project_id}/issues",
            {
                "title": title,
                "description": description,
                "labels": ",".join(labels),
            },
        )

    def _post_mr_comment(self, mr_iid: int, body: str) -> dict[str, Any]:
        return self._post(
            f"/api/v4/projects/{self._project_id}/merge_requests/{mr_iid}/notes",
            {"body": body},
        )

    def _receipt_comment(self, receipt: PolicyReceipt) -> str:
        return render_receipt(receipt)


def render_receipt(receipt: PolicyReceipt) -> str:
    """Render a PolicyReceipt as a Markdown comment (also used for previews)."""
    verdict_icon = "🔴" if receipt.verdict == Verdict.REACHABLE else "🟢"
    path_str = " -> ".join(receipt.path) if receipt.path else "no path found"
    breakdown = "\n".join(
        f"- `{r.name}` (+{r.weight}): {r.reason}"
        for r in receipt.triggered_rules
    )

    lines = [
        "## ReachGate Triage Receipt",
        "",
        f"**Verdict:** {verdict_icon} `{receipt.verdict.value}`",
        f"**Risk score:** {receipt.risk_score}",
        f"**Finding:** {receipt.occurrence_name} ({receipt.severity})",
        "",
        "### Graph path",
        "",
        render_mermaid_path(receipt),
        "",
        "```",
        path_str,
        "```",
    ]
    if receipt.path:
        lines.append(
            f"({receipt.hops} hop(s) from entry point `{receipt.entry_point}`)"
        )
    lines += [
        "",
        "### Rule breakdown",
        breakdown or "No rules triggered.",
        "",
        "<sub>Generated by ReachGate. "
        "Score = sum of rule weights, not a model confidence score.</sub>",
    ]
    return "\n".join(lines)


_NODE_ICONS = {"File": "📄", "Definition": "ƒ", "ImportedSymbol": "📦"}


def _mermaid_label(node: str) -> str:
    """Turn a path entry like 'File:src/a.js' into an icon-prefixed label."""
    kind, _, name = node.partition(":")
    if name:
        icon = _NODE_ICONS.get(kind, "")
        label = f"{icon} {name}".strip()
    else:
        label = node
    # Mermaid labels break on quotes; the rest is safe inside quoted labels.
    return label.replace('"', "'")


def render_mermaid_path(receipt: PolicyReceipt) -> str:
    """Render the graph path as a Mermaid flowchart (GitLab renders these inline)."""
    lines = ["```mermaid", "flowchart LR"]
    if receipt.path:
        for i, node in enumerate(receipt.path):
            lines.append(f'    n{i}["{_mermaid_label(node)}"]')
        for i in range(len(receipt.path) - 1):
            lines.append(f"    n{i} --> n{i + 1}")
        last = len(receipt.path) - 1
        lines.append("    classDef entry fill:#1f6feb,color:#fff,stroke:none;")
        lines.append("    classDef vuln fill:#da3633,color:#fff,stroke:none;")
        lines.append("    class n0 entry;")
        if last > 0:
            lines.append(f"    class n{last} vuln;")
    else:
        entry = _mermaid_label(receipt.entry_point or "declared entry points")
        target = _mermaid_label(
            receipt.vulnerable_definition or receipt.vulnerable_file or "finding"
        )
        lines.append(f'    e["🚪 {entry}"]')
        lines.append(f'    v["ƒ {target}"]')
        lines.append("    e -. no path found .- v")
        lines.append("    classDef entry fill:#1f6feb,color:#fff,stroke:none;")
        lines.append("    classDef safe fill:#2da44e,color:#fff,stroke:none;")
        lines.append("    class e entry;")
        lines.append("    class v safe;")
    lines.append("```")
    return "\n".join(lines)
