"""Take GitLab actions based on a PolicyReceipt."""

from __future__ import annotations

import json
import textwrap
from typing import Any

import httpx

from .policy_engine import PolicyReceipt, Verdict


class GitLabActions:
    def __init__(self, gitlab_url: str, token: str, project_id: int | str):
        self._base = gitlab_url.rstrip("/")
        self._project_id = project_id
        self._headers = {"PRIVATE-TOKEN": token, "Content-Type": "application/json"}

    def _post(self, path: str, body: dict[str, Any]) -> dict[str, Any]:
        resp = httpx.post(
            f"{self._base}{path}",
            headers=self._headers,
            json=body,
            timeout=15,
        )
        resp.raise_for_status()
        return resp.json()

    def handle(self, receipt: PolicyReceipt, mr_iid: int | None = None) -> dict[str, Any]:
        if receipt.verdict == Verdict.REACHABLE:
            return self._escalate(receipt, mr_iid)
        else:
            return self._deprioritize(receipt, mr_iid)

    def _escalate(self, receipt: PolicyReceipt, mr_iid: int | None) -> dict[str, Any]:
        body = self._receipt_comment(receipt)
        work_item = self._create_work_item(
            title=f"[ReachGate] Reachable: {receipt.occurrence_name}",
            description=body,
            labels=["reachgate::reachable", f"severity::{receipt.severity}"],
        )
        if mr_iid:
            self._post_mr_comment(mr_iid, body)
        return {"action": "escalated", "work_item": work_item}

    def _deprioritize(self, receipt: PolicyReceipt, mr_iid: int | None) -> dict[str, Any]:
        body = self._receipt_comment(receipt)
        if mr_iid:
            self._post_mr_comment(mr_iid, body)
        return {"action": "deprioritized"}

    def _create_work_item(
        self, title: str, description: str, labels: list[str]
    ) -> dict[str, Any]:
        return self._post(
            f"/api/v4/projects/{self._project_id}/issues",
            {
                "title": title,
                "description": description,
                "labels": ",".join(labels),
            },
        )

    def _post_mr_comment(self, mr_iid: int, body: str) -> dict[str, Any]:
        return self._post(
            f"/api/v4/projects/{self._project_id}/merge_requests/{mr_iid}/notes",
            {"body": body},
        )

    def _receipt_comment(self, receipt: PolicyReceipt) -> str:
        verdict_icon = "🔴" if receipt.verdict == Verdict.REACHABLE else "🟢"
        path_str = " -> ".join(receipt.path) if receipt.path else "no path found"
        breakdown = "\n".join(
            f"  - `{r.name}` (+{r.weight}): {r.reason}"
            for r in receipt.triggered_rules
        )
        return textwrap.dedent(f"""
            ## ReachGate Triage Receipt

            **Verdict:** {verdict_icon} `{receipt.verdict.value}`
            **Risk score:** {receipt.risk_score}
            **Finding:** {receipt.occurrence_name} ({receipt.severity})

            ### Graph path
            ```
            {path_str}
            ```
            ({receipt.hops} hop(s) from entry point `{receipt.entry_point}`)

            ### Rule breakdown
            {breakdown or "  No rules triggered."}

            <sub>Generated by ReachGate. Score = sum of rule weights, not a model confidence score.</sub>
        """).strip()
